CREATE TABLE IF NOT EXISTS COVID_SUMMARY.COUNTRY_STATISTICS (
  COUNTRY_CODE VARCHAR(2) PRIMARY KEY,
  COUNTRY VARCHAR(60) NOT NULL UNIQUE,
  SLUG VARCHAR(60) NOT NULL UNIQUE,
  NEW_CONFIRMED INT NOT NULL,
  TOTAL_CONFIRMED INT NOT NULL,
  NEW_DEATHS INT NOT NULL,
  TOTAL_DEATHS INT NOT NULL,
  NEW_RECOVERED INT NOT NULL,
  TOTAL_RECOVERED INT NOT NULL,
  STATISTIC_DATE DATETIME NOT NULL,
  UNIQUE INDEX COUNTRY_CODE_INDEX (COUNTRY_CODE ASC));
